// flow-typed signature: 790dc7bca56a2e4c1519f2f64d4e4ce7
// flow-typed version: <<STUB>>/@fortawesome/pro-light-svg-icons_v5.3.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/pro-light-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/pro-light-svg-icons' {
  declare module.exports: any;
}
