#
# Travis CI
# A distributed continuous integration service used to build and test projects hosted at GitHub.
#
# https://docs.travis-ci.com/
# https://docs.travis-ci.com/user/getting-started
# https://docs.travis-ci.com/user/customizing-the-build
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs
#
sudo: false
language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FA_TOKEN

before_script:
  - npm run lint
  - npm run flow
  - npm run test

script:
  - npm run build:prod
  - npm run build:storybook

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  all_branches: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build/storybook
  provider: pages
  skip_cleanup: true
