// flow-typed signature: 50072e9bfb48ac4666d16572c36d4555
// flow-typed version: <<STUB>>/enzyme-to-json_v3.5.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-to-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-to-json' {
  declare module.exports: any;
}
