// flow-typed signature: 7a63f58e89f96a52bfb4d1adc829f41d
// flow-typed version: <<STUB>>/lattice_v0.37.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice' {
  declare module.exports: any;
}
