// flow-typed signature: 42b08d044c10e410bbb6d411b8e50346
// flow-typed version: <<STUB>>/polished_v3.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polished'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polished' {
  declare module.exports: any;
}
