// flow-typed signature: 0561997f3f93f1a5aa4817ab62657c87
// flow-typed version: <<STUB>>/react-select_v2.4.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
  declare module.exports: any;
}
