// flow-typed signature: 6089d649e0ce0c0c4240e5624bd0b378
// flow-typed version: <<STUB>>/react-markdown_v6.0.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-markdown/react-markdown.min' {
  declare module.exports: any;
}

declare module 'react-markdown/src/ast-to-react' {
  declare module.exports: any;
}

declare module 'react-markdown/src/react-markdown' {
  declare module.exports: any;
}

declare module 'react-markdown/src/rehype-filter' {
  declare module.exports: any;
}

declare module 'react-markdown/src/uri-transformer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-markdown/react-markdown.min.js' {
  declare module.exports: $Exports<'react-markdown/react-markdown.min'>;
}
declare module 'react-markdown/src/ast-to-react.js' {
  declare module.exports: $Exports<'react-markdown/src/ast-to-react'>;
}
declare module 'react-markdown/src/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/src/react-markdown'>;
}
declare module 'react-markdown/src/rehype-filter.js' {
  declare module.exports: $Exports<'react-markdown/src/rehype-filter'>;
}
declare module 'react-markdown/src/uri-transformer.js' {
  declare module.exports: $Exports<'react-markdown/src/uri-transformer'>;
}
