// flow-typed signature: 3c3d9a4fa862512f5985c0de4f9ef087
// flow-typed version: <<STUB>>/react-scrolllock_v4.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scrolllock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scrolllock' {
  declare module.exports: any;
}
