// flow-typed signature: 6089d649e0ce0c0c4240e5624bd0b378
// flow-typed version: <<STUB>>/react-markdown_v6.0.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown' {
  declare module.exports: any;
}
