// flow-typed signature: 3638e2e6e302dc253e95824660f73d23
// flow-typed version: <<STUB>>/redux-reqseq_v0.1.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-reqseq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-reqseq' {
  declare module.exports: any;
}
