// flow-typed signature: 3d63b32b6d36622e8a06b348993fd26d
// flow-typed version: <<STUB>>/rehype-highlight_v4.1.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-highlight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rehype-highlight' {
  declare module.exports: any;
}
