// flow-typed signature: 2d710e38a45a52f7c8f945146f893ecf
// flow-typed version: <<STUB>>/remark-gfm_v1.0.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-gfm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-gfm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-gfm/index' {
  declare module.exports: $Exports<'remark-gfm'>;
}
declare module 'remark-gfm/index.js' {
  declare module.exports: $Exports<'remark-gfm'>;
}
