// flow-typed signature: 2707a97a932fe57ac803611101f95635
// flow-typed version: <<STUB>>/styled-components_v4.1.3/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}
