// flow-typed signature: 7ed29ef6da93a10ffdf64ee435c9faae
// flow-typed version: <<STUB>>/@material-ui/core_v4.5.2/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core' {
  declare module.exports: any;
}

declare module '@material-ui/core/styles' {
  declare module.exports: any;
}
