// flow-typed signature: a13bdd1d57cdd924624da6dae303f597
// flow-typed version: <<STUB>>/@material-ui/lab_v4.0.0-alpha.40/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/lab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/lab' {
  declare module.exports: any;
}
