// flow-typed signature: 961daa4d7c37688be7a4da00b615a7ba
// flow-typed version: <<STUB>>/@material-ui/pickers_v~3.2.10/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/pickers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/pickers' {
  declare module.exports: any;
}
