// flow-typed signature: 5f9d61d50037b50ea5904b8abd1b18ff
// flow-typed version: <<STUB>>/@material-ui/styles_v~4.9.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/styles' {
  declare module.exports: any;
}
